language: python
matrix:
  include:
    - name: Linux 64-bit
      sudo: required
      services:
        - docker
      env:
        - CIBW_SKIP=*manylinux1_i686*
        - CIBW_BUILD:cp3?-*
    - name: macOS
      os: osx
      language: generic
      env:
        - CIBW_BUILD:cp3?-*

script:
  - "pip install cibuildwheel==0.10.2 setuptools-rust==0.10.3"
  - export RUST_BACKTRACE=1
  - cibuildwheel --output-dir wheelhouse
